#https://github.com/terrakok/kmp-awesome
[versions]
# 务必同时更新VcatalogPlugin.kt中引用的版本号
gene-vcl = "2025.11.29"
gene-conventions = "2025.08.06"
build-config = "6.0.6"
plugin-publish = "2.0.0"
jetbrains-kotlin-jvm = "2.2.21"

[libraries]
gene-conventions = { module = "io.github.5hmlA:conventions", version.ref = "gene-conventions" }

[plugins]
# https://github.com/gmazzo/gradle-buildconfig-plugin
build-config  = { id = "com.github.gmazzo.buildconfig", version.ref = "build-config" }
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-kotlin-jvm" }